let bindings = {
  hide: "KeyH",
  delete: "KeyX",
  dupe: "KeyD",
  deselect: "Escape",
  debug: "Digit1",
  showControls: "Backquote",
  focusQuery: "KeyT",
  cancel: "KeyC",
  showBindings: "F1",
  save: "KeyS",
  undo: "KeyZ",
  undo2: "KeyY",
  viewChanges: "KeyK",
  shake: "Space",
  selectVisible: 'KeyA',
  resetDimensions: 'KeyR',
  resetAspectRatio: 'KeyU',
  pause: 'KeyP',
};
